project:
  type: website
  output-dir: _site

website:
  title: "neil birrell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd
#      - about.qmd
  open-graph: true
  twitter-card: true
  favicon: images/favicon.ico

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-in-header:
      - includes.html



