project:
  type: website
  output-dir: _site

website:
  title: "neilbirrell"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd
  open-graph: true
  twitter-card: true
  favicon: images/favicon.ico
  google-analytics: G-L3HC3XYXTE

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    include-in-header:
      - includes.html



