---
title: "Media"
draft: false # setting this to `true` will prevent your post from appearing on your listing page until you're ready!
---

I occasionally get asked to talk about insects as food and feed in the media. Here's a collection of media appearances:

#### 2024

[RNZ The Panel](https://www.rnz.co.nz/national/programmes/thepanel/audio/2018938704/the-panel-with-mark-knoff-thomas-and-paula-penfold-part-2) - Commentary on conspiracy theories around eating insects, and New Zealand attitudes towards eating insects.

#### 2022

[RNZ article](https://www.rnz.co.nz/news/country/466094/insect-protein-a-climate-friendly-alternative-to-meat-researchers-say) - Commentary on a recent paper on insect protein as a climate friendly alternative to meat

[RNZ Morning Rural News](https://www.rnz.co.nz/national/programmes/ruralnews/audio/2018839742/morning-rural-news-for-28-april-2022) - Commentary on a recent paper on insect protein as a climate friendly alternative to meat

[bFM: Tomorrow's World](https://95bfm.com/bcast/the-buzz-about-hexacycle-w-neil-birrell-june-27-2022) - Interview about black soldier fly organic waste treatment

#### 2021

[TVNZ](https://www.tvnz.co.nz/shows/bug-hunter-cooking-with-insects) - Bug Hunter: Cooking with Insects. I feature alongside my talented friend [Morgane Merien](https://morganemerien.com/)

[Stuff, NZ](https://www.stuff.co.nz/national/126470505/new-zealanders-open-to-eating-insects-study-finds) - An article on some of my research findings

[RNZ, Afternoons with Jesse Mulligan](https://www.rnz.co.nz/national/programmes/afternoons/audio/2018813997/appetite-for-insects-in-new-zealand) - Interview about my research findings

[Magic talk, Rural Today](https://omny.fm/shows/rural-today-catch-up-podcast/playlists/podcast/embed?style=cover) - Rural news piece on my research findings

[Magic Talk, AM show](https://omny.fm/shows/the-am-show-catchup-podcast/playlists/the-am-show-catchup-podcast/embed?style=cover)

[Ready steady learn, bFM](https://95bfm.com/bcast/ready-steady-learn-w-neil-birrell-september-21-2021) - Ways insects can help reduce our carbon emissions

#### 2019

[RNZ, Saturday Morning with Kim Hill](https://www.rnz.co.nz/national/programmes/saturday/audio/2018732320/wrangling-maggots-to-reduce-food-waste) - An interview on work in Kerala, India

[Green Desk: bFM](https://95bfm.com/bcast/the-green-desk-september-17-2019) - Interview about black soldier fly stuff

------------------------------------------------------